import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv('BOT_TOKEN')
TESTBOT_TOKEN = os.getenv('TESTBOT_TOKEN')

API_WEATHER_TOKEN = os.getenv('API_WEATHER_TOKEN')

ADMIN_ID = int(os.getenv('ADMIN_ID'))

API_KINOPOISK_TOKEN = os.getenv('API_KINOPOISK_TOKEN')
OTHER_API_KINOPOISK_TOKEN_1 = os.getenv('OTHER_API_KINOPOISK_TOKEN_1')
OTHER_API_KINOPOISK_TOKEN_2 = os.getenv('OTHER_API_KINOPOISK_TOKEN_2')
OTHER_API_KINOPOISK_TOKEN_3 = os.getenv('OTHER_API_KINOPOISK_TOKEN_3')
OTHER_API_KINOPOISK_TOKEN_4 = os.getenv('OTHER_API_KINOPOISK_TOKEN_4')
OTHER_API_KINOPOISK_TOKEN_5 = os.getenv('OTHER_API_KINOPOISK_TOKEN_5')

API_KINOPOISK_TOKEN_LIST = [
    API_KINOPOISK_TOKEN,
    OTHER_API_KINOPOISK_TOKEN_1,
    OTHER_API_KINOPOISK_TOKEN_2,
    OTHER_API_KINOPOISK_TOKEN_3,
    OTHER_API_KINOPOISK_TOKEN_4,
    OTHER_API_KINOPOISK_TOKEN_5
]
