"""added field active to users

Revision ID: e70b31b3a94d
Revises: dc5c5560a6d6
Create Date: 2024-11-02 15:42:11.030239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e70b31b3a94d"
down_revision: Union[str, None] = "dc5c5560a6d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    # ### end Alembic commands ###
